# Generated by Django 6.0.7 on 2026-08-01 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('college', 'College'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', '-date'),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('ai', 'AI / ML'), ('web', 'Web Development'), ('cloud', 'Cloud'), ('programming', 'Programming'), ('soft', 'Soft Skills'), ('other', 'Other')], default='ai', max_length=20)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('pdf_file', models.FileField(blank=True, help_text='Optional PDF for download.', null=True, upload_to='certificates/')),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('credential_url', models.URLField(blank=True, help_text='Verification link.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', '-issued_date'),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Leave empty if still studying.', null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ('order', '-start_year'),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for the current role.', null=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Extra matching words, comma separated.', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('achievements', 'Achievements'), ('hackathon', 'Hackathons'), ('workshop', 'Workshops'), ('college', 'College'), ('event', 'Events'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Anuj Biswal', max_length=120)),
                ('title', models.CharField(default='AI & Machine Learning Engineer', max_length=200)),
                ('tagline', models.TextField(blank=True, default='Building intelligent systems that solve real-world problems.')),
                ('bio', models.TextField(blank=True, help_text='Full biography for the About page.')),
                ('career_objective', models.TextField(blank=True)),
                ('journey', models.TextField(blank=True, help_text='Your story / how you started - About page.')),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('typing_roles', models.JSONField(blank=True, default=list, help_text='Roles animated in the hero, e.g. AI Engineer, Full-Stack Developer.')),
                ('interests', models.JSONField(blank=True, default=list, help_text='List of interests (chips on About page).')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ai', 'AI / ML'), ('web', 'Web Development'), ('app', 'Applications'), ('research', 'Research'), ('other', 'Other')], default='ai', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show on the home page.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('video_url', models.URLField(blank=True, help_text='Optional video (YouTube / MP4).')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True, help_text='Live demo link.')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='e.g. [Python, TensorFlow, Django]')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-featured', 'order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, default='Latest Resume', max_length=120)),
                ('file', models.FileField(help_text='PDF file.', upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(default='Anuj Biswal | AI & ML Engineer', max_length=200)),
                ('tagline', models.CharField(blank=True, default='AI Engineer & Full-Stack Developer', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='Portfolio of Anuj Biswal - AI/ML Engineer, Full-Stack Developer.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_color', models.CharField(default='#6c5ce7', help_text='Hex color, e.g. #6c5ce7', max_length=9)),
                ('accent_color', models.CharField(default='#00d4ff', help_text='Hex color, e.g. #00d4ff', max_length=9)),
                ('analytics_code', models.TextField(blank=True, help_text='Optional analytics snippet.')),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL for the contact page.')),
                ('footer_text', models.CharField(blank=True, default='(c) 2026 Anuj Biswal. Crafted with passion & code.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('ai', 'AI'), ('ml', 'Machine Learning'), ('cloud', 'Cloud'), ('programming', 'Programming'), ('database', 'Database'), ('tools', 'Tools'), ('soft', 'Soft Skills')], default='programming', max_length=20)),
                ('icon', models.CharField(blank=True, default='bi-code-slash', help_text='Bootstrap Icons class, e.g. bi-python', max_length=60)),
                ('level', models.PositiveIntegerField(default=70, help_text='0 - 100')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('category', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('slack', 'Slack'), ('twitter', 'Twitter / X'), ('leetcode', 'LeetCode'), ('codechef', 'CodeChef'), ('hackerrank', 'HackerRank'), ('youtube', 'YouTube'), ('medium', 'Medium'), ('portfolio', 'Portfolio')], max_length=20)),
                ('url', models.URLField(max_length=400)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'platform'),
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(default='/', max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-last_seen',),
            },
        ),
    ]
